name: habittrackerproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_crashlytics: ^4.1.5
  firebase_analytics: ^11.3.5
  firebase_messaging: ^15.1.5
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add assets here under the 'flutter' section
  assets:
    - assets/habit_logo.png
    - assets/habit_signup.png
